name = "SingularModes"
uuid = "630bf884-3bbe-4fe9-8bc5-255f673a196e"
authors = ["David Ba"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
